starting-money: 1000
maximum-vitality: 100.0
vitality-regeneration-per-minute: 2.0
activity-vitality-cost: 1.0

ranks:
  평민: 0
  남작: 500
  자작: 1500
  백작: 4000
  후작: 9000
  공작: 18000
  대공: 35000
  시장의 왕: 70000

activities:
  채집: [SWEET_BERRY_BUSH, SHORT_GRASS, TALL_GRASS, FERN, LARGE_FERN]
  농사: [WHEAT, CARROTS, POTATOES, BEETROOTS, NETHER_WART, COCOA]
  벌목: [OAK_LOG, SPRUCE_LOG, BIRCH_LOG, JUNGLE_LOG, ACACIA_LOG, DARK_OAK_LOG, MANGROVE_LOG, CHERRY_LOG]
  광업: [COAL_ORE, DEEPSLATE_COAL_ORE, IRON_ORE, DEEPSLATE_IRON_ORE, COPPER_ORE, DEEPSLATE_COPPER_ORE, GOLD_ORE, DEEPSLATE_GOLD_ORE, REDSTONE_ORE, DEEPSLATE_REDSTONE_ORE, LAPIS_ORE, DEEPSLATE_LAPIS_ORE, DIAMOND_ORE, DEEPSLATE_DIAMOND_ORE, EMERALD_ORE, DEEPSLATE_EMERALD_ORE]

market-prices:
  WHEAT: 8
  CARROT: 7
  POTATO: 7
  BEETROOT: 7
  OAK_LOG: 5
  SPRUCE_LOG: 5
  BIRCH_LOG: 5
  COD: 14
  SALMON: 18
  COAL: 10
  RAW_IRON: 24
  RAW_COPPER: 12
  RAW_GOLD: 35

quality-multipliers:
  1: 1.0
  2: 1.25
  3: 1.6
